require 'Items/ProceduralDistributions'

table.insert(ProceduralDistributions.list.MedicalClinicTools.items, "JCIO.SurgeonMag1")
table.insert(ProceduralDistributions.list.MedicalClinicTools.items, 10)
table.insert(ProceduralDistributions.list.MedicalStorageTools.items, "JCIO.SurgeonMag1")
table.insert(ProceduralDistributions.list.MedicalStorageTools.items, 10)
table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, "JCIO.SurgeonMag1")
table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, 10)
table.insert(ProceduralDistributions.list.SafehouseMedical.items, "JCIO.SurgeonMag1")
table.insert(ProceduralDistributions.list.SafehouseMedical.items, 10)

table.insert(ProceduralDistributions.list.MedicalClinicTools.items, "JCIO.SurgeonMag2")
table.insert(ProceduralDistributions.list.MedicalClinicTools.items, 10)
table.insert(ProceduralDistributions.list.MedicalStorageTools.items, "JCIO.SurgeonMag2")
table.insert(ProceduralDistributions.list.MedicalStorageTools.items, 10)
table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, "JCIO.SurgeonMag2")
table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, 10)
table.insert(ProceduralDistributions.list.SafehouseMedical.items, "JCIO.SurgeonMag2")
table.insert(ProceduralDistributions.list.SafehouseMedical.items, 10)

table.insert(ProceduralDistributions.list.MedicalClinicTools.items, "JCIO.SurgeonMag3")
table.insert(ProceduralDistributions.list.MedicalClinicTools.items, 10)
table.insert(ProceduralDistributions.list.MedicalStorageTools.items, "JCIO.SurgeonMag3")
table.insert(ProceduralDistributions.list.MedicalStorageTools.items, 10)
table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, "JCIO.SurgeonMag3")
table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, 10)
table.insert(ProceduralDistributions.list.SafehouseMedical.items, "JCIO.SurgeonMag3")
table.insert(ProceduralDistributions.list.SafehouseMedical.items, 10)

table.insert(ProceduralDistributions.list.MedicalClinicTools.items, "JCIO.ProthesisMag1")
table.insert(ProceduralDistributions.list.MedicalClinicTools.items, 5)
table.insert(ProceduralDistributions.list.MedicalStorageTools.items, "JCIO.ProthesisMag1")
table.insert(ProceduralDistributions.list.MedicalStorageTools.items, 5)
table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, "JCIO.ProthesisMag1")
table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, 5)
table.insert(ProceduralDistributions.list.SafehouseMedical.items, "JCIO.ProthesisMag1")
table.insert(ProceduralDistributions.list.SafehouseMedical.items, 5)
table.insert(ProceduralDistributions.list.StoreShelfMechanics.items, "JCIO.ProthesisMag1")
table.insert(ProceduralDistributions.list.StoreShelfMechanics.items, 5)
table.insert(ProceduralDistributions.list.MechanicShelfTools.items, "JCIO.ProthesisMag1")
table.insert(ProceduralDistributions.list.MechanicShelfTools.items, 5)

table.insert(ProceduralDistributions.list.MedicalClinicTools.items, "JCIO.ProthesisMag2")
table.insert(ProceduralDistributions.list.MedicalClinicTools.items, 5)
table.insert(ProceduralDistributions.list.MedicalStorageTools.items, "JCIO.ProthesisMag2")
table.insert(ProceduralDistributions.list.MedicalStorageTools.items, 5)
table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, "JCIO.ProthesisMag2")
table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, 5)
table.insert(ProceduralDistributions.list.SafehouseMedical.items, "JCIO.ProthesisMag2")
table.insert(ProceduralDistributions.list.SafehouseMedical.items, 5)
table.insert(ProceduralDistributions.list.StoreShelfMechanics.items, "JCIO.ProthesisMag2")
table.insert(ProceduralDistributions.list.StoreShelfMechanics.items, 5)
table.insert(ProceduralDistributions.list.MechanicShelfTools.items, "JCIO.ProthesisMag2")
table.insert(ProceduralDistributions.list.MechanicShelfTools.items, 5)

table.insert(ProceduralDistributions.list.MedicalClinicTools.items, "JCIO.ProthesisMag3")
table.insert(ProceduralDistributions.list.MedicalClinicTools.items, 5)
table.insert(ProceduralDistributions.list.MedicalStorageTools.items, "JCIO.ProthesisMag3")
table.insert(ProceduralDistributions.list.MedicalStorageTools.items, 5)
table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, "JCIO.ProthesisMag3")
table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, 5)
table.insert(ProceduralDistributions.list.SafehouseMedical.items, "JCIO.ProthesisMag3")
table.insert(ProceduralDistributions.list.SafehouseMedical.items, 5)
table.insert(ProceduralDistributions.list.StoreShelfMechanics.items, "JCIO.ProthesisMag3")
table.insert(ProceduralDistributions.list.StoreShelfMechanics.items, 5)
table.insert(ProceduralDistributions.list.MechanicShelfTools.items, "JCIO.ProthesisMag3")
table.insert(ProceduralDistributions.list.MechanicShelfTools.items, 5)