local t = require("harness.testkit")
local H = require("harness.init")

local CachedDataHandler = require("TOC/Handlers/CachedDataHandler")

t.describe("CachedDataHandler: cache operations", function()
    t.it("Setup creates an empty cache", function()
        H.initPlayer("Tester")
        local amputated = CachedDataHandler.GetAmputatedLimbs("Tester")
        t.assertTable(amputated)

        local count = 0
        for _ in pairs(amputated) do count = count + 1 end
        t.assertEquals(0, count)
    end)

    t.it("AddAmputatedLimb stores the limb", function()
        H.initPlayer("Tester")
        CachedDataHandler.AddAmputatedLimb("Tester", "Hand_L")
        local amputated = CachedDataHandler.GetAmputatedLimbs("Tester")
        t.assertTable(amputated)
        t.assertEquals("Hand_L", amputated["Hand_L"])
    end)

    t.it("GetAll exposes the expected structure", function()
        H.initPlayer("Tester")
        CachedDataHandler.CalculateCacheableValues("Tester")
        local all = CachedDataHandler.GetAll("Tester")
        t.assertTable(all)
        t.assertTable(all.amputatedLimbs)
        t.assertTable(all.highestAmputatedLimbs)
        t.assertTable(all.handFeasibility)
        t.assertBoolean(all.handFeasibility["L"])
        t.assertBoolean(all.handFeasibility["R"])
    end)
end)

t.describe("CachedDataHandler: hand feasibility", function()
    t.it("both hands feasible with no amputations", function()
        H.initPlayer("Tester")
        CachedDataHandler.CalculateCacheableValues("Tester")
        t.assertTrue(CachedDataHandler.GetHandFeasibility("L", "Tester"))
        t.assertTrue(CachedDataHandler.GetHandFeasibility("R", "Tester"))
        t.assertTrue(CachedDataHandler.GetBothHandsFeasibility("Tester"))
    end)

    t.it("left hand not feasible once cut", function()
        local dc = H.initPlayer("Tester")
        dc:setCutLimb("Hand_L", false, false, false, 0)
        CachedDataHandler.CalculateCacheableValues("Tester")
        t.assertFalse(CachedDataHandler.GetHandFeasibility("L", "Tester"))
        t.assertTrue(CachedDataHandler.GetHandFeasibility("R", "Tester"))
        t.assertTrue(CachedDataHandler.GetBothHandsFeasibility("Tester"))
    end)

    t.it("both hands not feasible once both cut", function()
        local dc = H.initPlayer("Tester")
        dc:setCutLimb("Hand_L", false, false, false, 0)
        dc:setCutLimb("Hand_R", false, false, false, 0)
        CachedDataHandler.CalculateCacheableValues("Tester")
        t.assertFalse(CachedDataHandler.GetHandFeasibility("L", "Tester"))
        t.assertFalse(CachedDataHandler.GetHandFeasibility("R", "Tester"))
        t.assertFalse(CachedDataHandler.GetBothHandsFeasibility("Tester"))
    end)

    t.it("feasible again once a prosthesis is equipped", function()
        local dc = H.initPlayer("Tester")
        dc:setCutLimb("Hand_L", false, false, false, 0)
        dc:setIsProstEquipped("Top_L", true)
        CachedDataHandler.CalculateCacheableValues("Tester")
        t.assertTrue(CachedDataHandler.GetHandFeasibility("L", "Tester"))
    end)
end)

t.describe("CachedDataHandler: highest amputated limbs", function()
    t.it("hand is the highest when only the hand is cut", function()
        local dc = H.initPlayer("Tester")
        dc:setCutLimb("Hand_L", false, false, false, 0)
        CachedDataHandler.CalculateHighestAmputatedLimbs("Tester")
        local highest = CachedDataHandler.GetHighestAmputatedLimbs("Tester")
        t.assertTable(highest)
        t.assertEquals("Hand_L", highest["L"])
        t.assertNil(highest["R"])
    end)

    t.it("forearm becomes the highest", function()
        local dc = H.initPlayer("Tester")
        dc:setCutLimb("ForeArm_L", false, false, false, 0)
        CachedDataHandler.CalculateHighestAmputatedLimbs("Tester")
        local highest = CachedDataHandler.GetHighestAmputatedLimbs("Tester")
        t.assertEquals("ForeArm_L", highest["L"])
    end)

    t.it("no highest when nothing is amputated", function()
        H.initPlayer("Tester")
        CachedDataHandler.CalculateHighestAmputatedLimbs("Tester")
        local highest = CachedDataHandler.GetHighestAmputatedLimbs("Tester")
        t.assertNil(highest["L"])
        t.assertNil(highest["R"])
    end)
end)
